# Game Profile: Everquest

# This profile defines settings, prompts, and overrides specifically for Everquest.
# It instructs the VLM on what visual information to focus on and how to generate commentary and advice.

general:
  game_name: "EverQuest"
  # Add any general settings specific to Everquest here
  # Example: capture_region: "main_game_window" # (This is conceptual, implementation might vary)

vlm_settings:
  # Model settings for the VLM. Can override global settings if needed.
  vlm_model: "deepseek-r1-0528-qwen3-8b"  # Upgraded to DeepSeek-R1 for enhanced reasoning
  vlm_max_tokens: 4096  # Much higher for reasoning model
  vlm_temperature: 0.3  # Lower for more focused reasoning
  vlm_max_commentary_sentences: 5  # Allow more detailed responses

# --- Vision Analysis Prompts (for Simple Vision screenshot analysis) ---
vision_prompts:
  action: "What EverQuest action is happening in this screenshot? Look for combat with monsters, spellcasting, meditation, looting, or player movement. Describe the specific EverQuest activity taking place."
  ui: "Describe the EverQuest UI elements visible: health/mana bars, chat windows, inventory, spellbook, target windows, or hotbars. What information is displayed in the EverQuest interface?"
  scene: "What EverQuest zone or environment is shown? Describe the setting: dungeon, outdoor zone, city, or specific landmark. What type of EverQuest location is this?"
  character: "Describe the EverQuest characters visible: player character class (warrior, wizard, cleric, etc.), NPCs, monsters, or other players. What EverQuest entities are in the scene?"
  combat: "Analyze the EverQuest combat situation: who is fighting whom, health levels, spell effects, or combat status. What's happening in this EverQuest battle?"
  everquest: "Provide detailed EverQuest analysis: identify the character class, current zone, combat status, group situation, and any important EverQuest gameplay elements visible. Give specific EverQuest context."
  quick: "Briefly describe this EverQuest gameplay screenshot in 1-2 sentences, focusing on the main EverQuest activity or situation."

prompts:
  # General system prompt (can be overridden by system_prompt_commentary or system_prompt_chat)
  system_prompt: |
    You are Danzar, an upbeat and witty gaming assistant who's always ready to help players crush their goals in EverQuest (or any game). 
    Speak casually, like a friendly raid leader—cheer people on, crack a clever joke now and then, and keep the energy high. 
    When giving advice, be forward-thinking: mention upcoming expansions, meta strategies, or ways to optimize both platinum farming and experience gains. 
    Use gamer lingo naturally, but explain anything arcane so newcomers feel included. 
    Above all, stay encouraging—everyone levels up at their own pace, and you're here to make the journey fun and rewarding.

  # System prompt specifically for VLM commentary based on image analysis
  system_prompt_commentary: |
    You are Danzar, an upbeat and witty EverQuest raid leader with deep knowledge of classic EverQuest mechanics, classes, zones, and gameplay. 
    
    You provide helpful, accurate commentary about what's happening on screen with the energy of a friendly guild leader. You understand:
    - All 14 EverQuest classes: Warrior, Cleric, Paladin, Ranger, Shadow Knight, Monk, Bard, Rogue, Wizard, Magician, Necromancer, Enchanter, Druid, Shaman
    - Combat mechanics: auto-attack, spell casting, meditation, skill training
    - Zone knowledge: newbie areas, dungeons, raid zones, faction areas
    - Death penalties: experience loss, corpse retrieval, binding locations
    - Group dynamics: tanking, healing, crowd control, DPS roles
    - Economic systems: tradeskills, buying/selling, bartering
    
    Keep responses concise (1-2 sentences) but enthusiastic and encouraging. Use gamer lingo naturally but explain anything complex. 
    Focus on actionable advice with that "let's crush this dungeon together" energy!

  # Template for the user message sent to the VLM, including image and OCR context
  user_prompt_template_commentary: |
    The game is {game_name}.
    Visible text on screen (OCR):
    {ocr_text}

    Based on the image and text, provide 1-2 key observations about the current EverQuest gameplay situation with your signature upbeat energy. 
    Focus on: character status, combat situation, location/zone, group dynamics, or strategic advice.
    Speak like a friendly raid leader cheering on the team!

  # Add other prompt sections as needed, e.g., for conversational chat
  system_prompt_chat: |
    You are Danzar, an upbeat and witty gaming assistant who's always ready to help players crush their goals in EverQuest (or any game). 
    Speak casually, like a friendly raid leader—cheer people on, crack a clever joke now and then, and keep the energy high. 
    When giving advice, be forward-thinking: mention upcoming expansions, meta strategies, or ways to optimize both platinum farming and experience gains. 
    Use gamer lingo naturally, but explain anything arcane so newcomers feel included. 
    Above all, stay encouraging—everyone levels up at their own pace, and you're here to make the journey fun and rewarding.
    
    If you don't know the answer based on the provided context, stay positive and let them know you're searching for more information!
    
    IMPORTANT: You are receiving voice transcriptions that may contain errors from speech-to-text processing. If a word or phrase seems out of context, unclear, or doesn't make sense, use your best judgment to interpret what the user likely meant based on the conversation context. Common STT errors include:
    - Homophones (e.g., 'there' vs 'their', 'to' vs 'too')
    - Similar-sounding words (e.g., 'game' vs 'gain', 'quest' vs 'test')
    - Missing or extra words
    - Punctuation errors
    - Background noise interpreted as words
    
    If you're unsure about a transcription, you can ask for clarification, but try to respond naturally to what you believe the user intended to say.

  conversational_max_tokens: 16384  # Maximum for DeepSeek-R1 reasoning model's full output
  conversational_temperature: 0.4  # Lower temperature for more focused reasoning
  conversational_llm_model: "deepseek-r1-0528-qwen3-8b"  # Explicitly set the reasoning model

  # Specific prompts or instructions related to analyzing visual elements.
  # These could be part of the main system prompt or used in specific VLM calls
  # depending on the implementation in llm_service.py. Kept for reference,
  # but the template above is the primary method for commentary.
  visual_analysis_instructions: |
    Analyze the provided game screenshot. Pay close attention to:
    - The health bars of the player and party members. Report critical health levels.
    - The mana bars of the player and party members. Comment on mana levels, especially for casters.
    - The health bar of the currently targeted enemy or NPC.
    - The main area of the screen to understand combat, movement, or interaction.
    Based on these observations, generate commentary and suggest actions or strategies.


# --- OCR Settings ---
ocr_settings:
  engine: "easyocr"
  easyocr_languages: ['en']
  easyocr_gpu: true
  default_upscale_factor: 2.0 
  default_grayscale: true
  default_binarize: true
  default_binarize_method: "otsu"
  default_confidence_threshold: 0.3  # Slightly higher for EQ's UI text

# Path to JSON file defining EverQuest-specific OCR regions
ocr_layout_path: "config/ui_layouts/everquest_ocr_layout.json"

# RAG for EverQuest knowledge (contains our populated knowledge base)
rag_collection_name: "Everquest"
rag_top_k: 3

# Reference image for EverQuest UI (optional)
reference_image_path: "config/ui_layouts/everquest_reference.png"

# Regions of interest for EverQuest VLM analysis
regions_of_interest:
  - name: "Chat Window"
    location_description: "the main chat area showing tells, says, guild chat, combat messages, and system notifications"
    vlm_instruction: "Look for important combat messages, death notifications, spell fizzles, faction messages, or player communication that might need attention."
  
  - name: "Character Stats"
    location_description: "the character window or stats display showing hit points, mana, stamina, and experience"
    vlm_instruction: "Check character health and mana levels. Note if health/mana is critically low or if the character needs to meditate."
  
  - name: "Spell Gems"
    location_description: "the 8 memorized spell slots showing currently prepared spells and their readiness"
    vlm_instruction: "Identify which spells are memorized and ready to cast. Note if important spells are missing or on cooldown."
  
  - name: "Target Window"
    location_description: "the target display showing the selected enemy or NPC with health bar and information"
    vlm_instruction: "Assess the target's health, level, and combat status. Note if it's a dangerous enemy or if combat is going well."
  
  - name: "Group Window"
    location_description: "the group member display showing party health, mana, and status"
    vlm_instruction: "Monitor group member health and mana. Identify if anyone needs healing or is in danger."
  
  - name: "Inventory/Bags"
    location_description: "character inventory slots and bag contents"
    vlm_instruction: "Check for important items, food for stamina, reagents for spells, or if inventory is full."
  
  - name: "Zone Information"
    location_description: "area showing current zone name, location, or environmental indicators"
    vlm_instruction: "Identify the current zone and assess if it's appropriate for the character's level or if there are zone-specific dangers."

# --- Short-Term Memory Settings ---
# Size of the in-memory deque for recent interactions
memory_deque_size: 5  # Slightly larger for complex EQ interactions

# RAG collection for chat history (optional, if you want to RAG user/bot turns)
# **IMPORTANT: Replace with your actual history collection name if you use one.**
# If you don't have a separate history RAG, you might not need this or rag_collection_name could serve double duty.
memory_rag_history_collection_name: "danzarvlm_everquest_history"

# Number of relevant VLM commentary memories to include in chat context (if using history RAG)
memory_rag_vlm_commentary_lookback_k: 3

# Number of relevant chat turn memories (user/bot) to include in chat context (if using history RAG)
memory_rag_chat_lookback_k: 5


# Add any other Everquest-specific overrides or settings here
# For example, specific keywords to listen for or UI element locations if needed for analysis.
# overrides:
#   ui_elements:
#     party_member_health_region: [x1, y1, x2, y2] # Conceptual - requires image processing
#     target_health_region: [x1, y1, x2, y2] 

# --- EverQuest-Specific Gameplay Settings ---
gameplay_focus:
  - "Class-specific advice based on detected character type"
  - "Zone-appropriate warnings and suggestions" 
  - "Combat situation assessment and recommendations"
  - "Group role fulfillment and coordination"
  - "Death recovery and corpse retrieval guidance"
  - "Faction and alignment considerations"

# Common EverQuest keywords for enhanced detection
everquest_keywords:
  classes: ["warrior", "cleric", "paladin", "ranger", "shadow knight", "monk", "bard", "rogue", "wizard", "magician", "necromancer", "enchanter", "druid", "shaman"]
  zones: ["qeynos", "freeport", "crushbone", "blackburrow", "guk", "sebilis", "chardok", "velious", "kunark", "antonica"]
  mechanics: ["meditate", "fizzle", "resist", "faction", "bind", "gate", "corpse", "train", "camp", "aggro"]
  stats: ["strength", "stamina", "agility", "dexterity", "wisdom", "intelligence", "charisma", "mana", "hitpoints"]

# Enhanced conversation context for EverQuest
conversation_context:
  game_era: "Classic EverQuest"
  expansion_awareness: "Focus on original zones and classic mechanics"
  player_assistance_style: "Experienced mentor providing practical advice"
  
# TTS Settings optimized for EverQuest commentary
tts_settings:
  voice_tone: "calm_informative"  # Less excited than action games
  speech_rate: 0.9  # Slightly slower for tactical information
  emphasis_on: ["danger", "death", "low health", "no mana", "faction hit"] 