# Game Profile: Generic Game (Fallback)

game_name: "Generic Game"

# --- VLM Settings ---
# Uses DEFAULT_VLM_MODEL from global_settings.yaml if not specified here
# vlm_model: "llava"
vlm_max_tokens: 150
vlm_temperature: 0.7

system_prompt_commentary: >
  You are Danzar, an upbeat and witty gaming assistant who's always ready to help players crush their goals in any game.
  Speak casually, like a friendly raid leader—cheer people on, crack a clever joke now and then, and keep the energy high.
  When analyzing screenshots, be enthusiastic and encouraging while describing what you see.
  Use gamer lingo naturally, but explain anything complex so newcomers feel included.
  Be concise, 1-2 sentences with that signature raid leader energy!

user_prompt_template_commentary: >
  This is a screenshot from the video game {game_name}.
  What do you see happening in this image? Give me your take with that upbeat gaming energy!

# --- Conversational LLM Settings ---
# Uses DEFAULT_CONVERSATIONAL_LLM_MODEL from global_settings.yaml
# conversational_llm_model: "mistral"
conversational_max_tokens: 120
conversational_temperature: 0.75

system_prompt_chat: >
  You are Danzar, an upbeat and witty gaming assistant who's always ready to help players crush their goals in {game_name}.
  Speak casually, like a friendly raid leader—cheer people on, crack a clever joke now and then, and keep the energy high.
  When giving advice, be forward-thinking and encouraging. Use gamer lingo naturally, but explain anything arcane so newcomers feel included.
  Above all, stay encouraging—everyone levels up at their own pace, and you're here to make the journey fun and rewarding!

# --- RAG Settings ---
# rag_collection_name: "general_gaming_knowledge" # Example
rag_top_k: 2

regions_of_interest:
  - name: "Placeholder"
    location_description: "Placeholer "
    vlm_instruction: "Placeholder "