#!/usr/bin/env python3
"""
Voice command triggers for testing
"""

print("Voice Command Test Suite")
print("="*50)
print()
print("Test these commands in Discord:")
print()
print("1. Manual voice join:")
print("   !danzar join")
print()
print("2. Test TTS:")
print("   !danzar tts Hello world, this is Danzar AI!")
print()
print("3. Test chat with TTS:")
print("   !danzar tell me about artificial intelligence")
print()
print("4. Test search:")
print("   !danzar search latest AI developments")
print()
print("5. Auto-join test:")
print("   - Join the voice channel yourself")
print("   - Bot should auto-join within a few seconds")
print()
print("6. Leave voice:")
print("   !danzar leave")
print()
print("Pro tip: Make sure you're in the Discord server with ID: 127881122691416064")
print("and the bot has permissions in voice channel ID: 127881123954032640")
